version: '2'
services:
  sip.orchestrator:
    image: watson-vg-docker-local.artifactory.swg-devops.com/cgw.sip.orchestrator:0.3.1-rc-1
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      # Uncomment and specify when the Conversation API is used
      - WATSON_CONVERSATION_WORKSPACE_ID=8aa8a0ab-cc94-4a05-ab38-f33de65cd346
      - WATSON_CONVERSATION_USERNAME=968579a4-d9ed-46b3-8492-e9a9bf555021
      - WATSON_CONVERSATION_PASSWORD=InWtiUpYhF1Z
      - WATSON_CONVERSATION_URL=https://gateway.watsonplatform.net/conversation/api
      
      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=finest

  media.relay:
    image: watson-vg-docker-local.artifactory.swg-devops.com/cgw.media.relay:0.3.1-rc-1
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USERNAME=3b36c01c-6dfb-4cb6-9a7f-ea4fafd1b2f1
      - WATSON_STT_PASSWORD=pPI1h4hcgExG
      - WATSON_STT_URL=https://stream.watsonplatform.net/speech-to-text/api

      # Creds for Bluemix TTS
      - WATSON_TTS_USERNAME=e48b9a83-98e2-4499-8db0-e09b2d8f2629
      - WATSON_TTS_PASSWORD=wIHJktWDn3Jp
      - WATSON_TTS_URL=https://stream.watsonplatform.net/text-to-speech/api
      - WATSON_TTS_VOICE=en-US_MichaelVoice

      # Uncomment the following three lines to enable call recording
      #- ENABLE_RECORDING=true
    #volumes:
      #- $PWD/recordings:/vgw-media-relay/recordings
