https://www.ibm.com/support/knowledgecenter/SS4U29/reporting.htmlversion: '2'
services:
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:latest
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      # Configure either an SOE or reporting interface to receive the transcriptions (or both)
      # SOE
      - WATSON_CONVERSATION_USERNAME=
      - WATSON_CONVERSATION_PASSWORD=
      - WATSON_CONVERSATION_URL=
       
      # Reporting
      - REPORTING_URL=
      - REPORTING_USERNAME=
      - REPORTING_PASSWORD=
      - REPORTING_TRANSCRIPTION_EVENT_INDEX=

  media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USERNAME=
      - WATSON_STT_PASSWORD=
      - WATSON_STT_URL=

